#!/bin/sh

# Get full path to auto_gk script's directory, works when run from any dir
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GATEKEEPER_PATH="${SCRIPT_DIR}/.."

if [ "$#" -ne 3 ] ;
        then
        echo "Usage: auto_gk [token] [repo] [current_version]"
        exit 1
fi

# Generate at https://github.com/settings/tokens
GH_TOKEN=$1
# org/repo
REPO=$2
VERSION=$3

if [ -z "${GH_TOKEN}" ]; then
        echo "GH_TOKEN variable is not set."
        exit 1
fi

if [ -z "${REPO}" ]; then
        echo "REPO variable is not set."
        exit 1
fi

ruby "$GATEKEEPER_PATH/gatekeeper.rb" \
        --token "$GH_TOKEN" \
        --repo "$REPO" \
        --release "RC-$VERSION" \
        --title "Release Candidate v$VERSION" \

ruby "$GATEKEEPER_PATH/rc_infotizer.rb" \
        --token "$GH_TOKEN" \
        --repo "$REPO" \
        --release "RC-$VERSION"
